spring:
    profiles:
        active: loc

    mvc:
        trailing-slash-match: true

server:
    port: 8080
    servlet:
        context-path: /
        session:
            persistent: false

# mybatis setting
mybatis:
    check-config-location: true
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*/*.xml

# 공공데이터 공휴일
apis:
    data: https://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/
    service:
        key: serviceKey