spring:
    config:
        activate:
            on-profile: loc

    devtools:
        livereload:
            enabled: true
        restart:
            enabled: false

    mvc:
        trailing-slash-match: true

    # datasource
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/calendar_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ${DB_USER}
        password: ${DB_PASS}

# swagger
springdoc:
    api-docs:
        path: /api-docs
        groups:
            enabled: true
    swagger-ui:
        path: /swagger-ui.html
        enabled: true
        groups-order: ASC
        tags-sorter: alpha
        operations-sorter: method
        display-request-duration: true
        doc-expansion: none
    cache:
        disabled: true
    model-and-view-allowed: true
    override-with-generic-response: false