spring:
    profiles:
        active: loc

    mvc:
        trailing-slash-match: true

server:
    port: 8080
    servlet:
        context-path: /
        session:
            persistent: false

# mybatis setting
mybatis:
    check-config-location: true
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/*/*.xml
